# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: reduction
# "service" is the name of this project. This will also be added to your AWS resource names.
service: categoryService

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-south-1
  environment:
    DYNAMO_TABLE: Categories
    BUCKET_NAME: category-images-nidhi-8417973113-dev
    SNS_TOPIC_ARN: arn:aws:sns:ap-south-1:511551295071:CategoryCleanupTopic
  iamRoleStatements:
    # i am roles for sns notification
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: arn:aws:sns:ap-south-1:511551295071:CategoryCleanupTopic
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem # added permission to update existing items
        - dynamodb:Scan
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:ap-south-1:511551295071:table/Categories
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource:
        - arn:aws:s3:::category-images-nidhi-8417973113-dev/*

resources:
  Resources:
    CategoryImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: category-images-nidhi-8417973113-dev
    CategoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Categories
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: fileName
            AttributeType: S
        KeySchema:
          - AttributeName: fileName
            KeyType: HASH
    # create SNS topic to send notifications when cateogory without imageUrl are deleted
    CategoryCleanupTopic:
      Type: AWS::SNS::Topic #type of resource
      Properties:
        TopicName: CategoryCleanupTopic #name of the topic
    # create SNS subscription to send notifications to the topic
    CategoryCleanupSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: arn:aws:sns:ap-south-1:511551295071:CategoryCleanupTopic
        Protocol: email
        Endpoint: crickethilightsadda@gmail.com  

functions:
  getUploadUrl:
    handler: handlers/getUploadUrl.getUploadUrl
    events:
      - httpApi:
          path: /upload-url
          method: post
  updateCategoryImage:
     handler: handlers/updateCategoryImage.updateCategoryImage
     events: 
      - s3:
          bucket: category-images-nidhi-8417973113-dev
          event: s3:ObjectCreated:Put
          existing: true
  cleanupCategories:
    handler: handlers/cleanupCategories.cleanupCategories
    events:
      - schedule:
          rate: rate(2 minutes)
          input:
            bucketName: category-images-nidhi-8417973113-dev
            tableName: Categories
